var SCFG={pending:{label:"Not Visited",color:"#6b7280",bg:"#374151",dot:"#9ca3af"},checked_in:{label:"Checked In",color:"#60a5fa",bg:"#1e3a5f",dot:"#3b82f6"},not_interested:{label:"Not Interested",color:"#f87171",bg:"#450a0a",dot:"#ef4444"},sale:{label:"SALE!",color:"#4ade80",bg:"#052e16",dot:"#16a34a"},callback:{label:"Call Back",color:"#fbbf24",bg:"#451a03",dot:"#f59e0b"},no_answer:{label:"No Answer",color:"#c084fc",bg:"#2e1065",dot:"#a855f7"}};
var BTYPES=["Restaurant","Medical","Laundry","Spa/Wellness","Auto","Bakery","Retail","Office","Gym","Hotel","Other"];
var SAMPLE=[{id:1,name:"Tim Hortons",address:"1240 King St W",type:"Restaurant",lat:43.642,lng:-79.434},{id:2,name:"Metro Dental",address:"882 College St",type:"Medical",lat:43.655,lng:-79.421},{id:3,name:"Sunrise Laundromat",address:"334 Roncesvalles Ave",type:"Laundry",lat:43.648,lng:-79.449},{id:4,name:"Bella Cucina",address:"567 Bloor St W",type:"Restaurant",lat:43.661,lng:-79.441},{id:5,name:"GreenLeaf Spa",address:"221 Ossington Ave",type:"Spa/Wellness",lat:43.652,lng:-79.431},{id:6,name:"Parkdale Auto",address:"1100 Queen St W",type:"Auto",lat:43.638,lng:-79.436},{id:7,name:"Corner Bakery",address:"489 Dufferin St",type:"Bakery",lat:43.644,lng:-79.445},{id:8,name:"Dr. Patel Chiro",address:"75 Runnymede Rd",type:"Medical",lat:43.651,lng:-79.461}];
function hav(a,b,c,d){var R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,p=Math.sin(x/2)*Math.sin(x/2)+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)*Math.sin(y/2);return R*2*Math.atan2(Math.sqrt(p),Math.sqrt(1-p));}
function fdist(k){return k<1?Math.round(k*1000)+"m":k.toFixed(1)+"km";}
function mkLead(l){return{id:l.id,name:l.name,address:l.address,type:l.type,lat:l.lat,lng:l.lng,status:"pending",checkInTime:null,checkOutTime:null,notes:"",checkedInAt:null};}
var state={leads:null,view:"list",gps:null,gpsOn:false,watchId:null,filter:"all",modal:null,modalNotes:"",coStatus:"not_interested",addOpen:false,newName:"",newAddr:"",newType:"Restaurant",newLat:null,newLng:null};
function load(){try{var s=localStorage.getItem("ow6");if(s)state.leads=JSON.parse(s);}catch(e){}if(!state.leads)state.leads=SAMPLE.map(mkLead);}
function save(){try{localStorage.setItem("ow6",JSON.stringify(state.leads));}catch(e){}}
function nearest(){if(!state.gps)return null;var p=state.leads.filter(function(l){return l.status=="pending";});if(!p.length)return null;var m=p.map(function(l){return{l:l,d:hav(state.gps.lat,state.gps.lng,l.lat,l.lng)};});m.sort(function(a,b){return a.d-b.d;});return{lead:m[0].l,dist:m[0].d};}
function calcStats(){var v=state.leads.filter(function(l){return l.status!="pending";}).length,s=state.leads.filter(function(l){return l.status=="sale";}).length;return{total:state.leads.length,visited:v,sales:s,ni:state.leads.filter(function(l){return l.status=="not_interested";}).length,cb:state.leads.filter(function(l){return l.status=="callback";}).length,na:state.leads.filter(function(l){return l.status=="no_answer";}).length,conv:v>0?Math.round(s/v*100):0};}
function startGps(){if(!navigator.geolocation){alert("GPS not available");return;}state.gpsOn=true;state.watchId=navigator.geolocation.watchPosition(function(p){state.gps={lat:p.coords.latitude,lng:p.coords.longitude};draw();},function(e){state.gpsOn=false;alert(e.code==1?"Location denied":"GPS error");draw();},{enableHighAccuracy:true,maximumAge:10000,timeout:15000});draw();}
function stopGps(){if(state.watchId!=null)navigator.geolocation.clearWatch(state.watchId);state.gps=null;state.gpsOn=false;draw();}
function draw(){
var st=calcStats(),nr=nearest(),h="";
h+="<div class=hdr><div class=logo><div class=logo-box>OW</div><div><div class=logo-text>OPTIMUM WATER</div><div class=logo-sub>FIELD SALES</div></div></div><div class=nav>";
h+="<button onclick=toggleGps() style=\"background:"+(state.gpsOn?"#2563eb":"#374151")+";color:"+(state.gpsOn?"white":"#9ca3af")+"\">"+(state.gpsOn?"GPS ON":"GPS")+"</button>";
["list","stats"].forEach(function(v){h+="<button onclick=\"setView('"+v+"')\" style=\"background:"+(state.view==v?"#2563eb":"#374151")+";color:"+(state.view==v?"white":"#9ca3af")+"\">"+v+"</button>";});
h+="</div></div>";
h+="<div class=statbar><div class=stat><span class=stat-label>Total</span><span class=stat-val style=\"color:#9ca3af\">"+st.total+"</span></div><div class=stat><span class=stat-label>Visited</span><span class=stat-val style=\"color:#60a5fa\">"+st.visited+"</span></div><div class=stat><span class=stat-label>Sales</span><span class=stat-val style=\"color:#4ade80\">"+st.sales+"</span></div><div class=stat><span class=stat-label>Conv</span><span class=stat-val style=\"color:"+(st.conv>=20?"#4ade80":"#fbbf24")+"\">"+st.conv+"%</span></div><div style=\"margin-left:auto;display:flex;gap:6px;flex-shrink:0\"><button onclick=openAdd() style=\"padding:6px 12px;background:#2563eb;border:none;border-radius:6px;color:white;font-size:11px;font-weight:700\">+ Add</button><button onclick=doReset() style=\"padding:6px 10px;background:transparent;border:1px solid #374151;border-radius:6px;color:#6b7280;font-size:11px\">Reset</button></div></div>";
if(nr&&state.view=="list"){h+="<div class=nearest-banner><div><div class=nb-label>NEAREST UNVISITED</div><div class=nb-name>"+nr.lead.name+"</div><div class=nb-addr>"+nr.lead.address+"</div></div><div><div class=nb-dist>"+fdist(nr.dist)+"</div><div class=nb-tap>away</div></div></div>";}
h+="<div class=main>";
if(state.view=="list"){
h+="<div class=filters>";
[["all","All"],["pending","Not Visited"],["checked_in","Checked In"],["sale","Sale"],["not_interested","Not Interested"],["callback","Callback"],["no_answer","No Answer"]].forEach(function(f){var on=state.filter==f[0];h+="<button onclick=\"setFilter('"+f[0]+"')\" style=\"background:"+(on?"#2563eb":"#374151")+";color:"+(on?"white":"#9ca3af")+"\">"+f[1]+"</button>";});
h+="</div>";
var shown=state.leads.slice();
if(state.filter!="all")shown=shown.filter(function(l){return l.status==state.filter;});
if(state.gps){shown=shown.map(function(l){return{l:l,d:hav(state.gps.lat,state.gps.lng,l.lat,l.lng)};});shown.sort(function(a,b){return a.d-b.d;});shown=shown.map(function(x){return x.l;});}
shown.forEach(function(lead){var cfg=SCFG[lead.status],isNr=nr&&nr.lead.id==lead.id,dist=state.gps?hav(state.gps.lat,state.gps.lng,lead.lat,lead.lng):null;h+="<div class=\"card"+(lead.status=="sale"?" sale":"")+(isNr?" nearest":"")+"\"><div class=card-top><div style=\"flex:1;min-width:0\"><div class=card-name>"+lead.name+"</div><div class=card-addr>"+lead.address+" - "+lead.type+"</div>"+(dist!=null?"<div class=card-dist>"+fdist(dist)+" away</div>":"")+(lead.notes?"<div style=\"font-size:9px;color:#6b7280;margin-top:3px;font-style:italic\">"+lead.notes+"</div>":"")+"</div><div style=\"display:flex;flex-direction:column;align-items:flex-end;gap:6px\"><div class=badge style=\"background:"+cfg.bg+"\"><span class=badge-dot style=\"background:"+cfg.dot+"\"></span><span class=badge-text style=\"color:"+cfg.color+"\">"+cfg.label+"</span></div>"+(lead.status=="pending"?"<button class=btn-checkin onclick=\"openIn("+lead.id+")\">Check In</button>":"")+(lead.status=="checked_in"?"<button class=btn-checkout onclick=\"openOut("+lead.id+")\">Check Out</button>":"")+"</div></div></div>";});
if(!shown.length)h+="<div style=\"text-align:center;padding:40px;color:#374151;font-size:12px\">No leads here</div>";
}
if(state.view=="stats"){
h+="<div class=sales-hero><div class=sales-num>"+st.sales+"</div><div class=sales-lbl>SALES TODAY</div><div class=sales-conv>"+st.conv+"% conversion rate</div></div><div class=stats-grid>";
[{l:"Visited",v:st.visited,t:st.total,c:"#60a5fa"},{l:"Not Interested",v:st.ni,t:st.visited||1,c:"#f87171"},{l:"Callbacks",v:st.cb,t:st.visited||1,c:"#fbbf24"},{l:"No Answer",v:st.na,t:st.visited||1,c:"#c084fc"}].forEach(function(s){h+="<div class=stats-card><div class=stats-big style=\"color:"+s.c+"\">"+s.v+"</div><div class=stats-lbl>"+s.l+"</div><div class=progress><div class=progress-bar style=\"width:"+Math.min(100,Math.round(s.v/(s.t||1)*100))+"%;background:"+s.c+"\"></div></div></div>";});
h+="</div>";
}
h+="</div>";
if(state.modal&&state.modal.mode=="in"){var ml=state.modal.lead;h+="<div class=overlay><div class=sheet><div class=sheet-title>CHECKING IN AT</div><div class=sheet-name>"+ml.name+"</div><div class=sheet-addr>"+ml.address+"</div><div class=notes-label>NOTES</div><textarea class=notes-input id=mnotes placeholder=\"Notes...\">"+state.modalNotes+"</textarea><div class=sheet-btns><button class=btn-confirm style=\"background:#2563eb\" onclick=confirmIn()>CONFIRM CHECK IN</button><button class=btn-cancel onclick=closeModal()>X</button></div></div></div>";}
if(state.modal&&state.modal.mode=="out"){var ml2=state.modal.lead;h+="<div class=overlay><div class=sheet><div class=sheet-title>CHECKING OUT OF</div><div class=sheet-name>"+ml2.name+"</div><div class=sheet-addr>"+ml2.address+"</div><div class=notes-label>OUTCOME</div><div class=outcome-grid>";["sale","not_interested","callback","no_answer"].forEach(function(s){var c2=SCFG[s],sel=state.coStatus==s;h+="<button class=\"outcome-btn"+(sel?" selected":"")+"\" style=\""+(sel?"background:"+c2.bg+";color:"+c2.color+";border-color:"+c2.dot+";":"")+"\" onclick=\"setCO('"+s+"')\">"+c2.label+"</button>";});var cbg=state.coStatus=="sale"?"#16a34a":state.coStatus=="callback"?"#d97706":"#dc2626";h+="</div><div class=notes-label>NOTES</div><textarea class=notes-input id=mnotes placeholder=\"Notes...\">"+state.modalNotes+"</textarea><div class=sheet-btns><button class=btn-confirm style=\"background:"+cbg+"\" onclick=confirmOut()>CONFIRM CHECK OUT</button><button class=btn-cancel onclick=closeModal()>X</button></div></div></div>";}
if(state.addOpen){h+="<div class=overlay><div class=sheet><div class=sheet-title>ADD NEW BUSINESS</div><div class=sheet-name style=\"font-size:15px\">Walk-in Lead</div><div class=field-label>BUSINESS NAME</div><input class=field-input id=newname value=\""+state.newName+"\" placeholder=\"e.g. Fresh Cut Barbershop\" oninput=\"state.newName=this.value\"/><div class=field-label>ADDRESS</div><input class=field-input id=newaddr value=\""+state.newAddr+"\" placeholder=\"e.g. 450 Queen St W\" oninput=\"state.newAddr=this.value\"/><div class=field-label>TYPE</div><select class=field-input onchange=\"state.newType=this.value\">";BTYPES.forEach(function(t){h+="<option"+(state.newType==t?" selected":"")+">"+t+"</option>";});var canAdd=state.newName.trim()&&state.newAddr.trim();h+="</select>"+(state.gps?"<div class=field-label>GPS</div><button onclick=tagGps() style=\"width:100%;padding:10px;background:"+(state.newLat?"#052e16":"#1f2937")+";border:2px solid "+(state.newLat?"#16a34a":"#374151")+";border-radius:8px;color:"+(state.newLat?"#4ade80":"#60a5fa")+";font-size:11px\">"+(state.newLat?"GPS Tagged":"Tag My Location")+"</button>":"")+"<div class=sheet-btns><button class=btn-confirm style=\"background:"+(canAdd?"#16a34a":"#374151")+";color:"+(canAdd?"white":"#6b7280")+"\" onclick=addBiz()>ADD TO ROUTE</button><button class=btn-cancel onclick=closeAdd()>X</button></div></div></div>";}
document.getElementById("r").innerHTML=h;
}
window.toggleGps=function(){state.gpsOn?stopGps():startGps();};
window.setView=function(v){state.view=v;draw();};
window.setFilter=function(f){state.filter=f;draw();};
window.doReset=function(){if(confirm("Reset all leads?")){state.leads=state.leads.map(function(l){return Object.assign({},l,{status:"pending",checkInTime:null,checkOutTime:null,notes:"",checkedInAt:null});});save();draw();}};
window.openIn=function(id){state.modal={lead:state.leads.find(function(l){return l.id==id;}),mode:"in"};state.modalNotes="";draw();};
window.openOut=function(id){var lead=state.leads.find(function(l){return l.id==id;});state.modal={lead:lead,mode:"out"};state.coStatus="not_interested";state.modalNotes=lead.notes||"";draw();};
window.closeModal=function(){state.modal=null;draw();};
window.setCO=function(s){state.coStatus=s;draw();};
window.confirmIn=function(){var n=document.getElementById("mnotes")?document.getElementById("mnotes").value:state.modalNotes;state.leads=state.leads.map(function(l){return l.id==state.modal.lead.id?Object.assign({},l,{status:"checked_in",checkInTime:new Date().toLocaleTimeString(),checkedInAt:Date.now(),notes:n}):l;});save();state.modal=null;draw();};
window.confirmOut=function(){var n=document.getElementById("mnotes")?document.getElementById("mnotes").value:state.modalNotes;state.leads=state.leads.map(function(l){return l.id==state.modal.lead.id?Object.assign({},l,{status:state.coStatus,checkOutTime:new Date().toLocaleTimeString(),notes:n}):l;});save();state.modal=null;draw();};
window.openAdd=function(){state.addOpen=true;state.newName="";state.newAddr="";state.newType="Restaurant";state.newLat=null;state.newLng=null;draw();};
window.closeAdd=function(){state.addOpen=false;draw();};
window.tagGps=function(){if(state.gps){state.newLat=state.gps.lat;state.newLng=state.gps.lng;draw();}};
window.addBiz=function(){var n=document.getElementById("newname")?document.getElementById("newname").value.trim():state.newName.trim(),a=document.getElementById("newaddr")?document.getElementById("newaddr").value.trim():state.newAddr.trim();if(!n||!a)return;var nl={id:Date.now(),name:n,address:a,type:state.newType,lat:state.newLat||(state.gps?state.gps.lat+(Math.random()-.5)*.003:43.649+(Math.random()-.5)*.02),lng:state.newLng||(state.gps?state.gps.lng+(Math.random()-.5)*.003:-79.435+(Math.random()-.5)*.03),status:"pending",checkInTime:null,checkOutTime:null,notes:"",checkedInAt:null};state.leads.push(nl);save();state.addOpen=false;draw();};
load();draw();
